# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "feature/internal-changes" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Build Regular Jar
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build

    - run: ${{ hashfiles(backup-code-generator/build/libs/backup-code-generator-1.0.0.jar) }} > backup-code-generator-1.0.0.jar.checksum.txt
    
    - name: Build Uber Jar
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: uberJar

    - run: ${{ hashfiles(backup-code-generator/build/libs/backup-code-generator-1.0.0-uber.jar) }} > backup-code-generator-1.0.0-uber.jar.checksum.txt

    - name: Upload artifacts
      uses: actions/upload-artifact@v3.1.3
      with: 
        path: |
          backup-code-generator/build/libs/backup-code-generator-1.0.0.jar
          backup-code-generator/build/uberJars/backup-code-generator-1.0.0-uber.jar
          backup-code-generator-1.0.0.jar.checksum.txt
          backup-code-generator-1.0.0-uber.jar.checksum.txt
